name: Repository Dispatch trigger

on:
  repository_dispatch:
    types: send_approval_email

jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}